### ISSUE TITLE
Dialogflow calls

### ISSUE THREAD

**Issue by galileoguzman** [signalwire/signalwire-python-old#60]
Hey guys, is there a way we can retrieve a Dialogflow call from `python-client`?

**Comment by bryanrite** [comment]
Currently the Python SDK cannot access Dialogflow calls, but in the near future, we will be releasing the ability to transfer calls from Dialogflow to LaML or Relay, where you will be able to control the call from there.

I will close this issue, but feel free to reopen if you have further comments. Thanks!

**Comment by donaldallen** [comment]
Hi @bryanrite, is it possible to do this yet?

**Comment by bryanrite** [comment]
@donaldallen Yes! You can setup a "Transfer Call" response for one of your Dialogflow intents and transfer it to a phone number (done via the Dialogflow UI). If that phone number is a SignalWire phone number, it'll get transferred to the specific phone number's inbound call handler. You'll get access to it the same way you would any inbound call.

**Comment by donaldallen** [comment]
@bryanrite So my project is using SignalWire’s one-click integration, but there’s no option to transfer a call unless I enable the DialogFlow Phone Gateway (beta) feature. Is that the right way to do this?

**Comment by bryanrite** [comment]
Yes, since Dialogflow is handling the intent and responses, the action to transfer comes from the Dialogflow agent. I believe you have to have the Dialog Telephone Gateway enabled (to be able to setup a Transfer Call action), but you don't need to use it for inbound phone numbers or anything like that. Feel free to reach out to SignalWire support or our Slack channel, they have resources, guides and can answer specific questions about setting this up! Thanks!
